name: we_connect_iui_mobile
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.9.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.13
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  image_picker: ^1.1.2
  intl: any
  package_info_plus: ^8.0.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/.env.dev
    - assets/images/
    - assets/images/onboarding/webinar_amico.png
    - assets/images/onboarding/push_notifications_cuate.png
    - assets/images/onboarding/mobile_login_amico.png
    - assets/images/onboarding/No-Image-Placeholder.svg
    - assets/images/onboarding/Profile_data_amico.png
    - assets/images/onboarding/Starting_a_business_project_amico.png
    - assets/images/onboarding/GDPR_amico.png
    - assets/images/logo/2.png
    - assets/images/logo/1-no_bg.png
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne/Syne-Regular.ttf
        - asset: assets/fonts/Syne/Syne-Medium.ttf
        - asset: assets/fonts/Syne/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne/Syne-ExtraBold.ttf
          weight: 800
    - family: Red_Hat_Display
      fonts:
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Regular.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Italic.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Medium.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-MediumItalic.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-SemiBold.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-SemiBoldItalic.ttf
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-BoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Red_Hat_Display/RedHatDisplay-ExtraBoldItalic.ttf
          weight: 800