name: we_connect_iui_mobile
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  intl: any
  supabase_flutter: ^2.5.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/onboarding/webinar_amico.png
    - assets/images/onboarding/push_notifications_cuate.png
    - assets/images/onboarding/mobile_login_amico.png
    - assets/images/onboarding/No-Image-Placeholder.svg
    - assets/images/onboarding/Profile_data_amico.png
    - assets/images/onboarding/Starting_a_business_project_amico.png
    - assets/images/onboarding/GDPR_amico.png
    - assets/images/logo/2.png
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
        - asset: assets/fonts/Syne-Medium.ttf
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800
