// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_FIREBASE_API_KEY']!,
    appId: '1:904544785591:web:96e0517d5551c105d2e932',
    messagingSenderId: '904544785591',
    projectId: 'weconnect-iui',
    authDomain: 'weconnect-iui.firebaseapp.com',
    storageBucket: 'weconnect-iui.appspot.com',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_FIREBASE_API_KEY']!,
    appId: '1:904544785591:android:fa3ac4255ba167d5d2e932',
    messagingSenderId: '904544785591',
    projectId: 'weconnect-iui',
    storageBucket: 'weconnect-iui.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_FIREBASE_API_KEY']!,
    appId: '1:904544785591:ios:4317ded412e1f146d2e932',
    messagingSenderId: '904544785591',
    projectId: 'weconnect-iui',
    storageBucket: 'weconnect-iui.appspot.com',
    iosBundleId: 'com.example.weConnectIuiMobile',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_FIREBASE_API_KEY']!,
    appId: '1:904544785591:ios:4317ded412e1f146d2e932',
    messagingSenderId: '904544785591',
    projectId: 'weconnect-iui',
    storageBucket: 'weconnect-iui.appspot.com',
    iosBundleId: 'com.example.weConnectIuiMobile',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_FIREBASE_API_KEY']!,
    appId: '1:904544785591:web:88bb639acaeb29c7d2e932',
    messagingSenderId: '904544785591',
    projectId: 'weconnect-iui',
    authDomain: 'weconnect-iui.firebaseapp.com',
    storageBucket: 'weconnect-iui.appspot.com',
  );
}
