name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:         
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Print the version
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Build APK
        run: flutter build apk
      
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: we-connect-app-${{ steps.get_version.outputs.VERSION }}
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: WeConnect-IUI-mobile ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: we-connect-app-${{ steps.get_version.outputs.VERSION }}

      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./we-connect-app-${{ steps.get_version.outputs.VERSION }}/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive